name: CI

on: 
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:

  lint:
    name: GO Linter
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  fmt:
    name: GO Format repo
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Format
        run: gofmt -d .
        working-directory: .

  test:
    name: GO Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Generate
        run: go generate ./...
        working-directory: .

      - name: Test
        run: go test ./...
        working-directory: .

  build:
    name: GO Build
    runs-on: ubuntu-latest
    needs: [lint,fmt,test]
    if: ${{ github.ref_name }} == "main"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run build
        run: go build . 
      