name: CI
on: 
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.5.2
      -
        name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20
      -
        name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      -
        name: Run build
        run: go build . 
      -
        name: Run vet & lint
        run: |
          go vet .
          golint .
